name: ocd_app
description: A new Flutter project. Focusing on creating an app to help the public learn more about Obsessive-Compulsive Disorder(OCD)

publish_to: 'none' # Remove this line if i wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP and other updated dependencies
  http: any
  collection: any
  crypto: any
  ffi: any
  http_parser: any
  leak_tracker: any
  material_color_utilities: any
  meta: any
  path_provider: any
  path_provider_android: any
  path_provider_foundation: any
  path_provider_windows: any
  platform: any
  string_scanner: 1.2.0
  test_api: any
  vm_service: ^13.0.0
  web: any
  win32: any

  # Other dependencies for the app
  english_words: any
  provider: any
  google_nav_bar: any
  google_fonts: any

# Development dependencies
dev_dependencies:
  flutter_launcher_icons: any  # Launcher icons for the app
  flutter_test:
    sdk: flutter
  flutter_lints: any

# Flutter launcher icons configuration
flutter_icons:
  android: true
  ios: true  # Ensure icons are enabled for both platforms
  image_path: "assets/icon/icon.png"

# Flutter project configurations
flutter:
  uses-material-design: true

  # Ensure assets are loaded properly
  assets:
     - assets/images/  # Load images from this directory
     
  # Fonts section for custom fonts
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
          weight: 700